name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "*" # Triggers on any tag push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up QEMU for multi-platform builds (optional but recommended)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          # Uses automatically provided GITHUB_TOKEN

      # 5. Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/chand1012/hooky:latest
            ghcr.io/chand1012/hooky:${{ github.sha }}
            ghcr.io/chand1012/hooky:${{ github.ref_name }}
